name: "Setup Ziti Build Environment"

inputs:
  ziti-ci-version:
    description: "The version of ziti-ci to use"
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: install ziti-ci
      shell: bash
      run: go install github.com/qrkourier/ziti-ci@${{ inputs.ziti-ci-version }}
